from ch10.str_str import str_str
from ch10.str_str_hash import str_str as str_str_hash
from ch10.longest_word_deleting import find_longest_word
from ch10.longest_word_deleting_dict import find_longest_word as find_longest_word_dict
from ch10.longest_happy_prefix import longest_prefix