from ch07.base import base
from ch07.pascals_triangle import pascals_triangle
from ch07.pascals_triangle_optimized import pascals_triangle as pascals_triangle_optimized
from ch07.perfect_squares import num_squares
from ch07.smallest_good_base import smallest_good_base, good_base
from ch07.smallest_good_base_math import smallest_good_base as smallest_good_base_math
from ch07.smallest_good_base_math import good_base as good_base_math
